/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var xQuery = (function () {
  var o = function (k, v, o, l) {
      for (o = o || {}, l = k.length; l--; o[k[l]] = v);
      return o;
    },
    $V0 = [1, 21],
    $V1 = [1, 19],
    $V2 = [1, 20],
    $V3 = [1, 22],
    $V4 = [1, 23],
    $V5 = [1, 24],
    $V6 = [1, 18],
    $V7 = [1, 13],
    $V8 = [1, 15],
    $V9 = [1, 16],
    $Va = [1, 17],
    $Vb = [1, 14],
    $Vc = [1, 12],
    $Vd = [5, 34, 40, 41, 42, 43, 44, 56, 60, 65, 67, 68, 72, 96],
    $Ve = [1, 36],
    $Vf = [1, 40],
    $Vg = [1, 52],
    $Vh = [1, 43],
    $Vi = [1, 44],
    $Vj = [1, 34],
    $Vk = [1, 45],
    $Vl = [1, 46],
    $Vm = [1, 47],
    $Vn = [1, 48],
    $Vo = [1, 49],
    $Vp = [1, 50],
    $Vq = [1, 51],
    $Vr = [1, 53],
    $Vs = [1, 54],
    $Vt = [1, 55],
    $Vu = [1, 56],
    $Vv = [1, 57],
    $Vw = [1, 58],
    $Vx = [1, 59],
    $Vy = [1, 60],
    $Vz = [1, 61],
    $VA = [
      5, 16, 18, 25, 29, 34, 39, 40, 41, 42, 43, 44, 54, 55, 56, 59, 60, 65, 67,
      68, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 88,
      89, 90, 91, 96,
    ],
    $VB = [1, 69],
    $VC = [1, 68],
    $VD = [1, 73],
    $VE = [1, 74],
    $VF = [1, 75],
    $VG = [1, 76],
    $VH = [1, 77],
    $VI = [1, 78],
    $VJ = [1, 79],
    $VK = [1, 80],
    $VL = [1, 81],
    $VM = [1, 82],
    $VN = [1, 83],
    $VO = [1, 84],
    $VP = [
      5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73, 74,
      75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 96,
    ],
    $VQ = [2, 82],
    $VR = [1, 87],
    $VS = [1, 85],
    $VT = [1, 86],
    $VU = [1, 88],
    $VV = [1, 89],
    $VW = [1, 90],
    $VX = [1, 91],
    $VY = [
      5, 25, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73,
      74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 88, 89, 90, 91, 96,
    ],
    $VZ = [
      5, 25, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 59, 60, 65, 67, 68, 71, 72,
      73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 88, 89, 90, 91,
      96,
    ],
    $V_ = [1, 95],
    $V$ = [1, 94],
    $V01 = [
      5, 16, 18, 25, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 59, 60, 65, 67, 68,
      71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 88, 89,
      90, 91, 96,
    ],
    $V11 = [2, 50],
    $V21 = [1, 101],
    $V31 = [
      5, 16, 18, 24, 25, 29, 34, 39, 40, 41, 42, 43, 44, 54, 55, 56, 59, 60, 65,
      67, 68, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87,
      88, 89, 90, 91, 96,
    ],
    $V41 = [1, 123],
    $V51 = [1, 144],
    $V61 = [5, 34, 39, 40, 41, 42, 43, 44, 56, 60, 65, 67, 68, 72, 96],
    $V71 = [
      5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73, 74,
      75, 76, 77, 78, 96,
    ],
    $V81 = [
      5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 75, 76,
      96,
    ],
    $V91 = [
      5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73, 74,
      75, 76, 77, 78, 79, 80, 96,
    ],
    $Va1 = [
      5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73, 74,
      75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 90, 91, 96,
    ];
  var parser = {
    trace: function trace() {},
    yy: {},
    symbols_: {
      error: 2,
      Init: 3,
      LExpresiones: 4,
      EOF: 5,
      Instrucciones: 6,
      HTMLSTRING: 7,
      For: 8,
      Return: 9,
      Let: 10,
      Where: 11,
      OrderBy: 12,
      If: 13,
      Valor: 14,
      Exp: 15,
      DIVSIGN: 16,
      Lexp: 17,
      ORSIGN: 18,
      Syntfin: 19,
      Fin: 20,
      "@": 21,
      Opc: 22,
      Preservada: 23,
      "::": 24,
      "*": 25,
      DIR: 26,
      TEXT: 27,
      "(": 28,
      ")": 29,
      NODE: 30,
      POSITION: 31,
      LAST: 32,
      DOC: 33,
      STRING: 34,
      DATA: 35,
      ExprLogica: 36,
      UPPERCASE: 37,
      SUBSTRING: 38,
      ",": 39,
      ID: 40,
      NUMBER: 41,
      STRING2: 42,
      DECIMAL: 43,
      VARIABLE: 44,
      CHILD: 45,
      DESCENDANT: 46,
      ANCESTOR: 47,
      PRECEDING: 48,
      FOLLOWING: 49,
      NAMESPACE: 50,
      SELF: 51,
      PARENT: 52,
      ATTR: 53,
      "[": 54,
      "]": 55,
      IF: 56,
      THEN: 57,
      Else: 58,
      ELSE: 59,
      FOR: 60,
      LFor: 61,
      IN: 62,
      ClauseExpr: 63,
      AT: 64,
      LET: 65,
      ":=": 66,
      WHERE: 67,
      ORDER: 68,
      BY: 69,
      LExp: 70,
      TO: 71,
      RETURN: 72,
      "<=": 73,
      ">=": 74,
      "=": 75,
      "!=": 76,
      ">": 77,
      "<": 78,
      EQ: 79,
      NE: 80,
      LT: 81,
      LE: 82,
      GT: 83,
      GE: 84,
      Expr: 85,
      "+": 86,
      "-": 87,
      DIV: 88,
      MOD: 89,
      OR: 90,
      AND: 91,
      ATRIBUTOS: 92,
      SUFIX: 93,
      "/>": 94,
      tk_llavea: 95,
      tk_llavec: 96,
      "</": 97,
      $accept: 0,
      $end: 1,
    },
    terminals_: {
      2: "error",
      5: "EOF",
      16: "DIVSIGN",
      18: "ORSIGN",
      21: "@",
      24: "::",
      25: "*",
      26: "DIR",
      27: "TEXT",
      28: "(",
      29: ")",
      30: "NODE",
      31: "POSITION",
      32: "LAST",
      33: "DOC",
      34: "STRING",
      35: "DATA",
      37: "UPPERCASE",
      38: "SUBSTRING",
      39: ",",
      40: "ID",
      41: "NUMBER",
      42: "STRING2",
      43: "DECIMAL",
      44: "VARIABLE",
      45: "CHILD",
      46: "DESCENDANT",
      47: "ANCESTOR",
      48: "PRECEDING",
      49: "FOLLOWING",
      50: "NAMESPACE",
      51: "SELF",
      52: "PARENT",
      53: "ATTR",
      54: "[",
      55: "]",
      56: "IF",
      57: "THEN",
      59: "ELSE",
      60: "FOR",
      62: "IN",
      64: "AT",
      65: "LET",
      66: ":=",
      67: "WHERE",
      68: "ORDER",
      69: "BY",
      71: "TO",
      72: "RETURN",
      73: "<=",
      74: ">=",
      75: "=",
      76: "!=",
      77: ">",
      78: "<",
      79: "EQ",
      80: "NE",
      81: "LT",
      82: "LE",
      83: "GT",
      84: "GE",
      86: "+",
      87: "-",
      88: "DIV",
      89: "MOD",
      90: "OR",
      91: "AND",
      92: "ATRIBUTOS",
      94: "/>",
      95: "tk_llavea",
      96: "tk_llavec",
      97: "</",
    },
    productions_: [
      0,
      [3, 2],
      [4, 2],
      [4, 1],
      [4, 1],
      [6, 1],
      [6, 1],
      [6, 1],
      [6, 1],
      [6, 1],
      [6, 1],
      [6, 1],
      [15, 2],
      [15, 1],
      [17, 4],
      [17, 3],
      [17, 1],
      [19, 1],
      [19, 3],
      [19, 3],
      [19, 3],
      [19, 2],
      [20, 2],
      [20, 2],
      [20, 3],
      [20, 3],
      [20, 3],
      [20, 3],
      [20, 4],
      [20, 4],
      [20, 4],
      [20, 8],
      [20, 2],
      [20, 2],
      [14, 1],
      [14, 1],
      [14, 1],
      [14, 1],
      [14, 1],
      [14, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [23, 1],
      [22, 3],
      [22, 0],
      [13, 7],
      [58, 2],
      [58, 0],
      [8, 2],
      [61, 5],
      [61, 7],
      [61, 3],
      [61, 5],
      [10, 4],
      [11, 2],
      [12, 3],
      [70, 3],
      [70, 1],
      [63, 1],
      [63, 5],
      [63, 5],
      [9, 2],
      [9, 2],
      [9, 2],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 3],
      [36, 1],
      [85, 3],
      [85, 3],
      [85, 3],
      [85, 3],
      [85, 3],
      [85, 3],
      [85, 3],
      [85, 3],
      [85, 1],
      [7, 4],
      [7, 3],
      [93, 1],
      [93, 7],
      [93, 4],
    ],
    performAction: function anonymous(
      yytext,
      yyleng,
      yylineno,
      yy,
      yystate /* action[1] */,
      $$ /* vstack */,
      _$ /* lstack */
    ) {
      /* this == yyval */

      var $0 = $$.length - 1;
      switch (yystate) {
        case 1:
          return $$[$0 - 1];

          break;
        case 2:
          $$[$0 - 1].push($$[$0]);
          this.$ = $$[$0 - 1];

          break;
        case 3:
          this.$ = [$$[$0]];

          break;
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
        case 16:
        case 17:
        case 52:
        case 91:
          this.$ = $$[$0];
          break;
        case 13:
          this.$ = $$[$0];
          break;
        case 22:
        case 90:
          this.$ = $$[$0 - 1];
          break;
        case 35:
          this.$ = new Literal(
            $$[$0],
            _$[$0].first_line,
            _$[$0].first_column,
            Type.NUMBER
          );

          break;
        case 36:
          this.$ = new Literal(
            $$[$0],
            _$[$0].first_line,
            _$[$0].first_column,
            Type.STRING
          );

          break;
        case 37:
          this.$ = new Literal(
            $$[$0],
            _$[$0].first_line,
            _$[$0].first_column,
            Type.STRING
          );

          break;
        case 38:
          this.$ = new Literal(
            $$[$0],
            _$[$0].first_line,
            _$[$0].first_column,
            Type.FLOAT
          );

          break;
        case 49:
          this.$ = $$[$0 - 2];
          break;
        case 51:
          this.$ = new If(
            $$[$0 - 4],
            $$[$0 - 1],
            $$[$0],
            _$[$0 - 6].first_line,
            _$[$0 - 6].first_column
          );

          break;
        case 70:
        case 79:
          this.$ = new Relational(
            $$[$0 - 2],
            $$[$0],
            RelationalOption.LESSOREQUAL,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 71:
        case 81:
          this.$ = new Relational(
            $$[$0 - 2],
            $$[$0],
            RelationalOption.GREATEROREQUAL,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 72:
        case 76:
          this.$ = new Relational(
            $$[$0 - 2],
            $$[$0],
            RelationalOption.EQUAL,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 73:
        case 77:
          this.$ = new Relational(
            $$[$0 - 2],
            $$[$0],
            RelationalOption.NOTEQUAL,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 74:
        case 80:
          this.$ = new Relational(
            $$[$0 - 2],
            $$[$0],
            RelationalOption.GREATER,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 75:
        case 78:
          this.$ = new Relational(
            $$[$0 - 2],
            $$[$0],
            RelationalOption.LESS,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 82:
          this.$ = $$[$0];
          break;
        case 83:
          this.$ = new Arithmetic(
            $$[$0 - 2],
            $$[$0],
            ArithmeticOption.PLUS,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 84:
          this.$ = new Arithmetic(
            $$[$0 - 2],
            $$[$0],
            ArithmeticOption.MINUS,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 85:
          this.$ = new Arithmetic(
            $$[$0 - 2],
            $$[$0],
            ArithmeticOption.TIMES,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 86:
          this.$ = new Arithmetic(
            $$[$0 - 2],
            $$[$0],
            ArithmeticOption.DIV,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 87:
          this.$ = new Arithmetic(
            $$[$0 - 2],
            $$[$0],
            ArithmeticOption.MOD,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 88:
          this.$ = new Logic(
            $$[$0 - 2],
            $$[$0],
            LogicOption.OR,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
        case 89:
          this.$ = new Logic(
            $$[$0 - 2],
            $$[$0],
            LogicOption.AND,
            _$[$0 - 2].first_line,
            _$[$0 - 2].first_column
          );

          break;
      }
    },
    table: [
      {
        3: 1,
        4: 2,
        6: 3,
        7: 4,
        8: 5,
        9: 6,
        10: 7,
        11: 8,
        12: 9,
        13: 10,
        14: 11,
        34: $V0,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        56: $V6,
        60: $V7,
        65: $V8,
        67: $V9,
        68: $Va,
        72: $Vb,
        78: $Vc,
      },
      { 1: [3] },
      {
        5: [1, 25],
        6: 26,
        8: 5,
        9: 6,
        10: 7,
        11: 8,
        12: 9,
        13: 10,
        14: 11,
        34: $V0,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        56: $V6,
        60: $V7,
        65: $V8,
        67: $V9,
        68: $Va,
        72: $Vb,
      },
      o($Vd, [2, 3]),
      o($Vd, [2, 4]),
      o($Vd, [2, 5]),
      o($Vd, [2, 6]),
      o($Vd, [2, 7]),
      o($Vd, [2, 8]),
      o($Vd, [2, 9]),
      o($Vd, [2, 10]),
      o($Vd, [2, 11]),
      { 40: [1, 27] },
      { 44: [1, 29], 61: 28 },
      {
        7: 32,
        13: 31,
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 30,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        56: $V6,
        78: $Vc,
        85: 33,
      },
      { 44: [1, 62] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 63,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      { 69: [1, 64] },
      { 28: [1, 65] },
      o($VA, [2, 34]),
      o($VA, [2, 35]),
      o($VA, [2, 36]),
      o($VA, [2, 37]),
      o($VA, [2, 38]),
      o($VA, [2, 39]),
      { 1: [2, 1] },
      o($Vd, [2, 2]),
      { 77: $VB, 92: [1, 66], 93: 67, 94: $VC },
      o($Vd, [2, 54], { 39: [1, 70] }),
      { 62: [1, 71], 64: [1, 72] },
      o($Vd, [2, 67], {
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($Vd, [2, 68]),
      o($Vd, [2, 69]),
      o($VP, $VQ, {
        25: $VR,
        86: $VS,
        87: $VT,
        88: $VU,
        89: $VV,
        90: $VW,
        91: $VX,
      }),
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 92,
      },
      o($VY, [2, 91]),
      {
        14: 42,
        17: 93,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      o($VZ, [2, 13], { 16: $V_, 18: $V$ }),
      o($V01, [2, 16]),
      o($V01, [2, 17]),
      {
        14: 96,
        23: 97,
        25: [1, 98],
        34: $V0,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      o($V01, $V11, { 22: 100, 24: [1, 99], 54: $V21 }),
      o($V01, $V11, { 22: 102, 54: $V21 }),
      o($V01, $V11, { 22: 103, 54: $V21 }),
      { 28: [1, 104] },
      { 28: [1, 105] },
      { 28: [1, 106] },
      { 28: [1, 107] },
      { 28: [1, 108] },
      { 28: [1, 109] },
      { 28: [1, 110] },
      { 28: [1, 111] },
      o($V01, $V11, { 22: 112, 54: $V21 }),
      o($V31, [2, 40]),
      o($V31, [2, 41]),
      o($V31, [2, 42]),
      o($V31, [2, 43]),
      o($V31, [2, 44]),
      o($V31, [2, 45]),
      o($V31, [2, 46]),
      o($V31, [2, 47]),
      o($V31, [2, 48]),
      { 66: [1, 113] },
      o($Vd, [2, 60], {
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      {
        14: 42,
        15: 115,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        70: 114,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 116,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      { 77: $VB, 93: 117, 94: $VC },
      o($Vd, [2, 93]),
      o($Vd, [2, 94]),
      { 95: [1, 118], 97: [1, 119] },
      { 44: [1, 120] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $V41,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 122,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        63: 121,
        85: 33,
      },
      { 44: [1, 124] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 125,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 126,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 127,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 128,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 129,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 130,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 131,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 132,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 133,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 134,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 135,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 136,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 137,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 138,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 139,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 140,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 141,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 142,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 143,
      },
      {
        25: $VR,
        29: $V51,
        86: $VS,
        87: $VT,
        88: $VU,
        89: $VV,
        90: $VW,
        91: $VX,
      },
      o($VZ, [2, 12], { 16: $V_, 18: $V$ }),
      { 16: [1, 145] },
      {
        14: 42,
        19: 146,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      o($V01, $V11, { 22: 147, 54: $V21 }),
      o($V01, $V11, { 22: 148, 54: $V21 }),
      o($V01, [2, 21]),
      {
        14: 42,
        20: 149,
        23: 150,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      o($V01, [2, 32]),
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 151,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      o($V01, [2, 22]),
      o($V01, [2, 23]),
      { 29: [1, 152] },
      { 29: [1, 153] },
      { 29: [1, 154] },
      { 29: [1, 155] },
      { 34: [1, 156] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 157,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 158,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 159,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      o($V01, [2, 33]),
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $V41,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 122,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        63: 160,
        85: 33,
      },
      o($Vd, [2, 61], { 39: [1, 161] }),
      o($V61, [2, 63]),
      {
        29: [1, 162],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      o($Vd, [2, 92]),
      {
        4: 163,
        6: 3,
        7: 4,
        8: 5,
        9: 6,
        10: 7,
        11: 8,
        12: 9,
        13: 10,
        14: 11,
        34: $V0,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        56: $V6,
        60: $V7,
        65: $V8,
        67: $V9,
        68: $Va,
        72: $Vb,
        78: $Vc,
      },
      { 40: [1, 164] },
      { 62: [1, 165], 64: [1, 166] },
      o($V61, [2, 57]),
      o($V61, [2, 64], {
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 167,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 168,
      },
      { 62: [1, 169] },
      o($V71, [2, 70], {
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($V71, [2, 71], {
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($V81, [2, 72], {
        73: $VD,
        74: $VE,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($V81, [2, 73], {
        73: $VD,
        74: $VE,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($V71, [2, 74], {
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($V71, [2, 75], {
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      }),
      o($V91, [2, 76], { 81: $VL, 82: $VM, 83: $VN, 84: $VO }),
      o($V91, [2, 77], { 81: $VL, 82: $VM, 83: $VN, 84: $VO }),
      o($VP, [2, 78]),
      o($VP, [2, 79]),
      o($VP, [2, 80]),
      o($VP, [2, 81]),
      o($Va1, [2, 83], { 25: $VR, 88: $VU, 89: $VV }),
      o($Va1, [2, 84], { 25: $VR, 88: $VU, 89: $VV }),
      o($VY, [2, 85]),
      o($VY, [2, 86]),
      o($VY, [2, 87]),
      o(
        [
          5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73,
          74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 90, 96,
        ],
        [2, 88],
        { 25: $VR, 86: $VS, 87: $VT, 88: $VU, 89: $VV, 91: $VX }
      ),
      o(
        [
          5, 29, 34, 39, 40, 41, 42, 43, 44, 55, 56, 60, 65, 67, 68, 71, 72, 73,
          74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 90, 91, 96,
        ],
        [2, 89],
        { 25: $VR, 86: $VS, 87: $VT, 88: $VU, 89: $VV }
      ),
      o($VY, [2, 90]),
      {
        14: 42,
        19: 170,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      o($V01, [2, 15]),
      o($V01, [2, 18]),
      o($V01, [2, 20]),
      o($V01, [2, 19]),
      o($V01, $V11, { 22: 100, 54: $V21 }),
      {
        55: [1, 171],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      o($V01, [2, 24]),
      o($V01, [2, 25]),
      o($V01, [2, 26]),
      o($V01, [2, 27]),
      { 29: [1, 172] },
      {
        29: [1, 173],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      {
        29: [1, 174],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      {
        39: [1, 175],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      o($Vd, [2, 59]),
      {
        14: 42,
        15: 176,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      { 57: [1, 177] },
      {
        6: 26,
        8: 5,
        9: 6,
        10: 7,
        11: 8,
        12: 9,
        13: 10,
        14: 11,
        34: $V0,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        56: $V6,
        60: $V7,
        65: $V8,
        67: $V9,
        68: $Va,
        72: $Vb,
        96: [1, 178],
      },
      { 77: [1, 179] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $V41,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 122,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        63: 180,
        85: 33,
      },
      { 44: [1, 181] },
      {
        39: [1, 183],
        71: [1, 182],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      o([39, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84], $VQ, {
        25: $VR,
        29: $V51,
        86: $VS,
        87: $VT,
        88: $VU,
        89: $VV,
        90: $VW,
        91: $VX,
      }),
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $V41,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 122,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        63: 184,
        85: 33,
      },
      o($V01, [2, 14]),
      o($V01, [2, 49]),
      o($V01, [2, 28]),
      o($V01, [2, 29]),
      o($V01, [2, 30]),
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 185,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      o($V61, [2, 62]),
      {
        14: 42,
        15: 186,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      { 97: [1, 187] },
      o($Vd, [2, 96]),
      o($V61, [2, 55]),
      { 62: [1, 188] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 189,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 190,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      o($V61, [2, 58]),
      {
        39: [1, 191],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      o($Vd, [2, 53], { 58: 192, 59: [1, 193] }),
      { 40: [1, 194] },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $V41,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 122,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        63: 195,
        85: 33,
      },
      {
        29: [1, 196],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      {
        29: [1, 197],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      {
        14: 42,
        15: 35,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        28: $Vj,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        36: 198,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
        85: 33,
      },
      o($Vd, [2, 51]),
      {
        14: 42,
        15: 199,
        16: $Ve,
        17: 37,
        19: 38,
        20: 39,
        21: $Vf,
        23: 41,
        25: $Vg,
        26: $Vh,
        27: $Vi,
        30: $Vk,
        31: $Vl,
        32: $Vm,
        33: $Vn,
        34: $V0,
        35: $Vo,
        37: $Vp,
        38: $Vq,
        40: $V1,
        41: $V2,
        42: $V3,
        43: $V4,
        44: $V5,
        45: $Vr,
        46: $Vs,
        47: $Vt,
        48: $Vu,
        49: $Vv,
        50: $Vw,
        51: $Vx,
        52: $Vy,
        53: $Vz,
      },
      { 77: [1, 200] },
      o($V61, [2, 56]),
      o($V61, [2, 65]),
      o($V61, [2, 66]),
      {
        29: [1, 201],
        73: $VD,
        74: $VE,
        75: $VF,
        76: $VG,
        77: $VH,
        78: $VI,
        79: $VJ,
        80: $VK,
        81: $VL,
        82: $VM,
        83: $VN,
        84: $VO,
      },
      o($Vd, [2, 52]),
      o($Vd, [2, 95]),
      o($V01, [2, 31]),
    ],
    defaultActions: { 25: [2, 1] },
    parseError: function parseError(str, hash) {
      if (hash.recoverable) {
        this.trace(str);
      } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
      }
    },
    parse: function parse(input) {
      var self = this,
        stack = [0],
        tstack = [],
        vstack = [null],
        lstack = [],
        table = this.table,
        yytext = "",
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;
      var args = lstack.slice.call(arguments, 1);
      var lexer = Object.create(this.lexer);
      var sharedState = { yy: {} };
      for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
          sharedState.yy[k] = this.yy[k];
        }
      }
      lexer.setInput(input, sharedState.yy);
      sharedState.yy.lexer = lexer;
      sharedState.yy.parser = this;
      if (typeof lexer.yylloc == "undefined") {
        lexer.yylloc = {};
      }
      var yyloc = lexer.yylloc;
      lstack.push(yyloc);
      var ranges = lexer.options && lexer.options.ranges;
      if (typeof sharedState.yy.parseError === "function") {
        this.parseError = sharedState.yy.parseError;
      } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
      }
      function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
      }
      _token_stack: var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        if (typeof token !== "number") {
          token = self.symbols_[token] || token;
        }
        return token;
      };
      var symbol,
        preErrorSymbol,
        state,
        action,
        a,
        r,
        yyval = {},
        p,
        len,
        newState,
        expected;
      while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
          action = this.defaultActions[state];
        } else {
          if (symbol === null || typeof symbol == "undefined") {
            symbol = lex();
          }
          action = table[state] && table[state][symbol];
        }
        if (typeof action === "undefined" || !action.length || !action[0]) {
          var errStr = "";
          expected = [];
          for (p in table[state]) {
            if (this.terminals_[p] && p > TERROR) {
              expected.push("'" + this.terminals_[p] + "'");
            }
          }
          if (lexer.showPosition) {
            errStr =
              "Parse error on line " +
              (yylineno + 1) +
              ":\n" +
              lexer.showPosition() +
              "\nExpecting " +
              expected.join(", ") +
              ", got '" +
              (this.terminals_[symbol] || symbol) +
              "'";
          } else {
            errStr =
              "Parse error on line " +
              (yylineno + 1) +
              ": Unexpected " +
              (symbol == EOF
                ? "end of input"
                : "'" + (this.terminals_[symbol] || symbol) + "'");
          }
          this.parseError(errStr, {
            text: lexer.match,
            token: this.terminals_[symbol] || symbol,
            line: lexer.yylineno,
            loc: yyloc,
            expected: expected,
          });
        }
        if (action[0] instanceof Array && action.length > 1) {
          throw new Error(
            "Parse Error: multiple actions possible at state: " +
              state +
              ", token: " +
              symbol
          );
        }
        switch (action[0]) {
          case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
              yyleng = lexer.yyleng;
              yytext = lexer.yytext;
              yylineno = lexer.yylineno;
              yyloc = lexer.yylloc;
              if (recovering > 0) {
                recovering--;
              }
            } else {
              symbol = preErrorSymbol;
              preErrorSymbol = null;
            }
            break;
          case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
              first_line: lstack[lstack.length - (len || 1)].first_line,
              last_line: lstack[lstack.length - 1].last_line,
              first_column: lstack[lstack.length - (len || 1)].first_column,
              last_column: lstack[lstack.length - 1].last_column,
            };
            if (ranges) {
              yyval._$.range = [
                lstack[lstack.length - (len || 1)].range[0],
                lstack[lstack.length - 1].range[1],
              ];
            }
            r = this.performAction.apply(
              yyval,
              [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack,
              ].concat(args)
            );
            if (typeof r !== "undefined") {
              return r;
            }
            if (len) {
              stack = stack.slice(0, -1 * len * 2);
              vstack = vstack.slice(0, -1 * len);
              lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
          case 3:
            return true;
        }
      }
      return true;
    },
  };

  let valDeclaration = "";
  let valTag = "";
  let valInside = "";
  const { Error_ } = require("../Error");
  const { errores } = require("../Errores");
  const { NodoXML } = require("../Nodes/NodoXml");

  // Expresiones
  const { Relational, RelationalOption } = require("../Expression/Relational");
  const { Arithmetic, ArithmeticOption } = require("../Expression/Arithmetic");
  const { Logic, LogicOption } = require("../Expression/Logic");
  const { Literal } = require("../Expression/Literal");
  // Instrucciones
  const { If } = require("../Instruction/If");

  // Extra
  const { Type } = require("../Abstract/Retorno");

  /* generated by jison-lex 0.3.4 */
  var lexer = (function () {
    var lexer = {
      EOF: 1,

      parseError: function parseError(str, hash) {
        if (this.yy.parser) {
          this.yy.parser.parseError(str, hash);
        } else {
          throw new Error(str);
        }
      },

      // resets the lexer, sets new input
      setInput: function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = "";
        this.conditionStack = ["INITIAL"];
        this.yylloc = {
          first_line: 1,
          first_column: 0,
          last_line: 1,
          last_column: 0,
        };
        if (this.options.ranges) {
          this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
      },

      // consumes and returns one char from the input
      input: function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno++;
          this.yylloc.last_line++;
        } else {
          this.yylloc.last_column++;
        }
        if (this.options.ranges) {
          this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
      },

      // unshifts one char (or a string) into the input
      unput: function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
          this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
          first_line: this.yylloc.first_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.first_column,
          last_column: lines
            ? (lines.length === oldLines.length
                ? this.yylloc.first_column
                : 0) +
              oldLines[oldLines.length - lines.length].length -
              lines[0].length
            : this.yylloc.first_column - len,
        };

        if (this.options.ranges) {
          this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
      },

      // When called from action, caches matched text and appends it on next action
      more: function () {
        this._more = true;
        return this;
      },

      // When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
      reject: function () {
        if (this.options.backtrack_lexer) {
          this._backtrack = true;
        } else {
          return this.parseError(
            "Lexical error on line " +
              (this.yylineno + 1) +
              ". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n" +
              this.showPosition(),
            {
              text: "",
              token: null,
              line: this.yylineno,
            }
          );
        }
        return this;
      },

      // retain first n characters of the match
      less: function (n) {
        this.unput(this.match.slice(n));
      },

      // displays already matched input, i.e. for error messages
      pastInput: function () {
        var past = this.matched.substr(
          0,
          this.matched.length - this.match.length
        );
        return (
          (past.length > 20 ? "..." : "") + past.substr(-20).replace(/\n/g, "")
        );
      },

      // displays upcoming input, i.e. for error messages
      upcomingInput: function () {
        var next = this.match;
        if (next.length < 20) {
          next += this._input.substr(0, 20 - next.length);
        }
        return (next.substr(0, 20) + (next.length > 20 ? "..." : "")).replace(
          /\n/g,
          ""
        );
      },

      // displays the character position where the lexing error occurred, i.e. for error messages
      showPosition: function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
      },

      // test the lexed token: return FALSE when not a match, otherwise return token
      test_match: function (match, indexed_rule) {
        var token, lines, backup;

        if (this.options.backtrack_lexer) {
          // save context
          backup = {
            yylineno: this.yylineno,
            yylloc: {
              first_line: this.yylloc.first_line,
              last_line: this.last_line,
              first_column: this.yylloc.first_column,
              last_column: this.yylloc.last_column,
            },
            yytext: this.yytext,
            match: this.match,
            matches: this.matches,
            matched: this.matched,
            yyleng: this.yyleng,
            offset: this.offset,
            _more: this._more,
            _input: this._input,
            yy: this.yy,
            conditionStack: this.conditionStack.slice(0),
            done: this.done,
          };
          if (this.options.ranges) {
            backup.yylloc.range = this.yylloc.range.slice(0);
          }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
          this.yylineno += lines.length;
        }
        this.yylloc = {
          first_line: this.yylloc.last_line,
          last_line: this.yylineno + 1,
          first_column: this.yylloc.last_column,
          last_column: lines
            ? lines[lines.length - 1].length -
              lines[lines.length - 1].match(/\r?\n?/)[0].length
            : this.yylloc.last_column + match[0].length,
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
          this.yylloc.range = [this.offset, (this.offset += this.yyleng)];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(
          this,
          this.yy,
          this,
          indexed_rule,
          this.conditionStack[this.conditionStack.length - 1]
        );
        if (this.done && this._input) {
          this.done = false;
        }
        if (token) {
          return token;
        } else if (this._backtrack) {
          // recover context
          for (var k in backup) {
            this[k] = backup[k];
          }
          return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
      },

      // return next match in input
      next: function () {
        if (this.done) {
          return this.EOF;
        }
        if (!this._input) {
          this.done = true;
        }

        var token, match, tempMatch, index;
        if (!this._more) {
          this.yytext = "";
          this.match = "";
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
          tempMatch = this._input.match(this.rules[rules[i]]);
          if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
            match = tempMatch;
            index = i;
            if (this.options.backtrack_lexer) {
              token = this.test_match(tempMatch, rules[i]);
              if (token !== false) {
                return token;
              } else if (this._backtrack) {
                match = false;
                continue; // rule action called reject() implying a rule MISmatch.
              } else {
                // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                return false;
              }
            } else if (!this.options.flex) {
              break;
            }
          }
        }
        if (match) {
          token = this.test_match(match, rules[index]);
          if (token !== false) {
            return token;
          }
          // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
          return false;
        }
        if (this._input === "") {
          return this.EOF;
        } else {
          return this.parseError(
            "Lexical error on line " +
              (this.yylineno + 1) +
              ". Unrecognized text.\n" +
              this.showPosition(),
            {
              text: "",
              token: null,
              line: this.yylineno,
            }
          );
        }
      },

      // return next match that has a token
      lex: function lex() {
        var r = this.next();
        if (r) {
          return r;
        } else {
          return this.lex();
        }
      },

      // activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
      begin: function begin(condition) {
        this.conditionStack.push(condition);
      },

      // pop the previously active lexer condition state off the condition stack
      popState: function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
          return this.conditionStack.pop();
        } else {
          return this.conditionStack[0];
        }
      },

      // produce the lexer rule set which is active for the currently active lexer condition state
      _currentRules: function _currentRules() {
        if (
          this.conditionStack.length &&
          this.conditionStack[this.conditionStack.length - 1]
        ) {
          return this.conditions[
            this.conditionStack[this.conditionStack.length - 1]
          ].rules;
        } else {
          return this.conditions["INITIAL"].rules;
        }
      },

      // return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
      topState: function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
          return this.conditionStack[n];
        } else {
          return "INITIAL";
        }
      },

      // alias for begin(condition)
      pushState: function pushState(condition) {
        this.begin(condition);
      },

      // return the number of states currently on the stack
      stateStackSize: function stateStackSize() {
        return this.conditionStack.length;
      },
      options: { "case-sensitive": true },
      performAction: function anonymous(
        yy,
        yy_,
        $avoiding_name_collisions,
        YY_START
      ) {
        var YYSTATE = YY_START;
        switch ($avoiding_name_collisions) {
          case 0 /*se ignoran*/:
            break;
          case 1:
            return 43;
            break;
          case 2:
            return 41;
            break;
          case 3:
            return 34;
            break;
          case 4:
            return 42;
            break;
          case 5:
            return 16;
            break;
          case 6:
            return 26;
            break;
          case 7:
            return 47;
            break;
          case 8:
            return 49;
            break;
          case 9:
            return 48;
            break;
          case 10:
            return 18;
            break;
          case 11:
            return 21;
            break;
          case 12:
            return 25;
            break;
          case 13:
            return 24;
            break;
          case 14:
            return 66;
            break;
          case 15:
            return 87;
            break;
          case 16:
            return 86;
            break;
          case 17:
            return 39;
            break;
          case 18:
            return 97;
            break;
          case 19:
            return 73;
            break;
          case 20:
            return 74;
            break;
          case 21:
            return 78;
            break;
          case 22:
            return 77;
            break;
          case 23:
            return 76;
            break;
          case 24:
            return 75;
            break;
          case 25:
            return 90;
            break;
          case 26:
            return 91;
            break;
          case 27:
            return 89;
            break;
          case 28:
            return 88;
            break;
          case 29:
            return 28;
            break;
          case 30:
            return 29;
            break;
          case 31:
            return 54;
            break;
          case 32:
            return 55;
            break;
          case 33:
            return 95;
            break;
          case 34:
            return 96;
            break;
          case 35:
            return 45;
            break;
          case 36:
            return 53;
            break;
          case 37:
            return 46;
            break;
          case 38:
            return 50;
            break;
          case 39:
            return 52;
            break;
          case 40:
            return 51;
            break;
          case 41:
            return 27;
            break;
          case 42:
            return 32;
            break;
          case 43:
            return 31;
            break;
          case 44:
            return 30;
            break;
          case 45:
            return 79;
            break;
          case 46:
            return 80;
            break;
          case 47:
            return 81;
            break;
          case 48:
            return 82;
            break;
          case 49:
            return 83;
            break;
          case 50:
            return 84;
            break;
          case 51:
            return 33;
            break;
          case 52:
            return 60;
            break;
          case 53:
            return 62;
            break;
          case 54:
            return 72;
            break;
          case 55:
            return 64;
            break;
          case 56:
            return 62;
            break;
          case 57:
            return 71;
            break;
          case 58:
            return 65;
            break;
          case 59:
            return 67;
            break;
          case 60:
            return 68;
            break;
          case 61:
            return 69;
            break;
          case 62:
            return 56;
            break;
          case 63:
            return 57;
            break;
          case 64:
            return 59;
            break;
          case 65:
            return 35;
            break;
          case 66:
            return 37;
            break;
          case 67:
            return "SUBSTRING";
            break;
          case 68:
            return 40;
            break;
          case 69:
            return 44;
            break;
          case 70:
            return 5;
            break;
        }
      },
      rules: [
        /^(?:[ \t\n\r\f])/,
        /^(?:([0-9]+(\.[0-9]+)?))/,
        /^(?:([0-9]+))/,
        /^(?:(([\"][^"]*[\"])))/,
        /^(?:(([\'][^\']*[\'])))/,
        /^(?:((\/)(\/)?))/,
        /^(?:((\.)(\.)?))/,
        /^(?:((ancestor)(-or-self)?))/,
        /^(?:((following)(-sibling)?))/,
        /^(?:((preceding)(-sibling)?))/,
        /^(?:((\|)(\|)?))/,
        /^(?:@)/,
        /^(?:\*)/,
        /^(?:::)/,
        /^(?::=)/,
        /^(?:-)/,
        /^(?:\+)/,
        /^(?:,)/,
        /^(?:<\/)/,
        /^(?:<=)/,
        /^(?:>=)/,
        /^(?:<)/,
        /^(?:>)/,
        /^(?:!=)/,
        /^(?:=)/,
        /^(?:or\b)/,
        /^(?:and\b)/,
        /^(?:mod\b)/,
        /^(?:div\b)/,
        /^(?:\()/,
        /^(?:\))/,
        /^(?:\[)/,
        /^(?:\])/,
        /^(?:\{)/,
        /^(?:\})/,
        /^(?:child\b)/,
        /^(?:attribute\b)/,
        /^(?:descendant\b)/,
        /^(?:namespace\b)/,
        /^(?:parent\b)/,
        /^(?:self\b)/,
        /^(?:text\b)/,
        /^(?:last\b)/,
        /^(?:position\b)/,
        /^(?:node\b)/,
        /^(?:eq\b)/,
        /^(?:ne\b)/,
        /^(?:lt\b)/,
        /^(?:le\b)/,
        /^(?:gt\b)/,
        /^(?:ge\b)/,
        /^(?:doc\b)/,
        /^(?:for\b)/,
        /^(?:in\b)/,
        /^(?:return\b)/,
        /^(?:at\b)/,
        /^(?:in\b)/,
        /^(?:to\b)/,
        /^(?:let\b)/,
        /^(?:where\b)/,
        /^(?:order\b)/,
        /^(?:by\b)/,
        /^(?:if\b)/,
        /^(?:then\b)/,
        /^(?:else\b)/,
        /^(?:data\b)/,
        /^(?:upper-case\b)/,
        /^(?:substring\b)/,
        /^(?:([a-zA-Z_])[a-zA-Z0-9_ñÑ.]*)/,
        /^(?:(\$)([a-zA-Z_])[a-zA-Z0-9_ñÑ.]*)/,
        /^(?:$)/,
      ],
      conditions: {
        INITIAL: {
          rules: [
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
            36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
            53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
            70,
          ],
          inclusive: true,
        },
      },
    };
    return lexer;
  })();
  parser.lexer = lexer;
  function Parser() {
    this.yy = {};
  }
  Parser.prototype = parser;
  parser.Parser = Parser;
  return new Parser();
})();

if (typeof require !== "undefined" && typeof exports !== "undefined") {
  exports.parser = xQuery;
  exports.Parser = xQuery.Parser;
  exports.parse = function () {
    return xQuery.parse.apply(xQuery, arguments);
  };
  exports.main = function commonjsMain(args) {
    if (!args[1]) {
      console.log("Usage: " + args[0] + " FILE");
      process.exit(1);
    }
    // var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    // return exports.parser.parse(source);
  };
  if (typeof module !== "undefined" && require.main === module) {
    exports.main(process.argv.slice(1));
  }
}
